#!/bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        2
bspc config window_gap          20

bspc config split_ratio          0.625
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config pointer_follows_focus false

# bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Sxiv state=floating follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

# startup
bash "$HOME"/scripts/startup.sh

