#!/bin/sh

sxhkd &

bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8
bspc monitor eDP-1-1 -d 9 10

bspc config border_width        5
bspc config normal_border_color "#c678dd"
bspc config focused_border_color "#56b6c2"
bspc config window_gap          40

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config focus_follows_pointer true

bspc rule -a Sxiv state=floating follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
# bspc rule -a "GNU Image Manipulation Program" state=floating

# btops &

# startup
bash "$HOME"/scripts/startup.sh

xset b off
