# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Export
export ZSH="$HOME/.oh-my-zsh"
export PATH=$HOME/bin:/usr/local/bin:$PATH
export MANPATH="/usr/local/man:$MANPATH"
export LANG=en_US.UTF-8
export PATH="/usr/local/sbin:$PATH"
export PATH="/home/uzen/bin/:$PATH"


# Settings
ZSH_THEME="powerlevel10k/powerlevel10k"
# CASE_SENSITIVE="true"
HYPHEN_INSENSITIVE="true"
# DISABLE_AUTO_UPDATE="true"
# DISABLE_UPDATE_PROMPT="true"
# export UPDATE_ZSH_DAYS=13
# DISABLE_MAGIC_FUNCTIONS=true
# DISABLE_LS_COLORS="true"
# DISABLE_AUTO_TITLE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
# DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="mm/dd/yyyy"

# Plugin
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Aliases
alias df="source ~/scripts/dfolder.sh"
alias asa="source ~/scripts/asa.sh"
alias cfg="source ~/scripts/cfg.sh"
alias rmt="rmtrash"
alias init="nvim ~/.config/nvim/init.vim"
alias plugin="nvim ~/.config/nvim/plugin.vim"
alias upower="upower -i /org/freedesktop/UPower/devices/battery_BAT0"
alias surf="bash ~/.surf/surf-open.sh"
alias clip="xsel --clipboard --input"
alias cclip="cat | clip"
alias t="todo.sh"

# VIM
bindkey -v
export KEYTIMEOUT=1

# Pywal
(cat ~/.cache/wal/sequences &)
source ~/.cache/wal/colors-tty.sh

# Personal Settings
export EDITOR="/usr/bin/nvim"
export VISUAL="/usr/bin/nvim"

alias tetris="cd ~/bin/Tetris && ./Tetris"
alias wechat="wine \"$HOME/.wine/drive_c/Program Files (x86)/Tencent/WeChat/WeChat.exe\""
alias zhumu="wine $HOME/.wine/drive_c/users/uzen/Application\ Data/Zhumu\ Cloud\ Meetings/bin/zhumu.exe"
alias dictg="dict -d gcide "
alias wal="wal --backend colorz -i "
alias nt="nvim *.tex"
alias db="bash $HOME/scripts/save_page_as -b firefox"
alias tt="bash $HOME/scripts/timetable.sh"
alias cw="cd \"$HOME/.wine/drive_c/Program Files (x86)\""
alias mc="java -jar /opt/shiginima/shiginima.jar"

unsetopt share_history

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
